src/DataCollection/Models/Tagihan.cs
using FastMember;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DataCollection.Models
{
    public class Tagihan
    {
        [Ordinal(0)]
        public int Id { get; set; }

        [DisplayName("Nama PIC")]
        [Required]
        [Ordinal(1)]
        public string NamaPenagih { get; set; }

        [DisplayName("Nama Aplikasi")]
        [Required]
        [Ordinal(2)]
        public string NamaAplikasi { get; set; }

        [DisplayName("Nama Nasabah")]
        [Required]
        [Ordinal(3)]
        public string NamaNasabah { get; set; }

        [DisplayName("User Aplikasi")]
        [Required]
        [Ordinal(4)]
        public string UserAplikasi { get; set; }

        [DisplayName("Nomor ID")]
        [Required]
        [Ordinal(5)]
        public string IDNumber { get; set; }

        [DisplayName("Telat")]
        [Required]
        [Ordinal(6)]
        public decimal Telat { get; set; }

        [DisplayName("Nomor Telepon")]
        [Required]
        [Ordinal(7)]
        public string NomorTelepon { get; set; }

        [DisplayName("Atas Nama")]
        [Required]
        [Ordinal(8)]
        public string NomorTeleponNama { get; set; }

        [DisplayName("Tagihan Pokok")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        [Required]
        [Ordinal(9)]
        public decimal TagihanPokok { get; set; }

        [DisplayName("Tagihan Terbayar")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        [Required]
        [Ordinal(10)]
        public decimal TagihanTerbayar { get; set; }

        [DisplayName("Tipe Pembayaran")]
        [Required]
        [Ordinal(11)]
        public string TipePembayaran { get; set; }

        [DataType(DataType.Date)]
        [DisplayName("Tanggal Pembayaran")]
        [Required]
        [Ordinal(12)]
        public DateTime TanggalPembayaran { get; set; }

        [Ordinal(13)]
        public decimal KomisiPercent { get; set; }

        [DisplayFormat(DataFormatString = "{0:C0}")]
        [Ordinal(14)]
        public decimal KomisiNominal { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy H:mm:ss}")]
        [Ordinal(15)]
        public DateTime CreatedTime { get; set; }

        [NotMapped]
        [Ordinal(16)]
        public IEnumerable<IFormFile> Files { get; set; }

        [Ordinal(17)]
        public string CreatedBy_Name { get; set; }
    }
}

src/DataCollection/Controllers/TagihanController.cs
using DataCollection.Models;
using DataCollection.ViewModels;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using OfficeOpenXml;
using OfficeOpenXml.Table;
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using NPOI.SS.UserModel;
using NPOI.HSSF.UserModel;
using NPOI.XSSF.UserModel;

namespace DataCollection.Controllers
{
    [Authorize]
    public class TagihanController : ParentController
    {
        private IHostingEnvironment _hostingEnvironment;
        private const string XlsxContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        private readonly IMapper _mapper;
        private IModelRepository _repository;
        private ILogger<TagihanController> _logger;

        public TagihanController(IModelRepository Repository, IMapper Mapper, ILogger<TagihanController> Logger, 
            IHostingEnvironment hostingEnvironment)
        {
            _repository = Repository;
            _logger = Logger;
            _mapper = Mapper;
            _hostingEnvironment = hostingEnvironment;
        }

        //[HttpPost]
        //public IActionResult ImportExcel(IFormFile file)
        //{
        //    var errorTagihan = new List<Tagihan>();
        //    string folderName = "UploadExcel";
        //    string webRootPath = _hostingEnvironment.WebRootPath;
        //    string newPath = Path.Combine(webRootPath, folderName);
        //    StringBuilder sb = new StringBuilder();
        //    if (!Directory.Exists(newPath))
        //    {
        //        Directory.CreateDirectory(newPath);
        //    }
        //    if (file != null)
        //    {
        //        int count = 1;
        //        List<string> dataArray = new List<string>();
        //        string sFileExtension = Path.GetExtension(file.FileName).ToLower();
        //        string sFileName = Path.GetFileNameWithoutExtension(file.FileName);
        //        string fullPath = Path.Combine(newPath, file.FileName);
        //        string fileUrl = MyHttpContext.AppBaseUrl + "/" + folderName + "/" + file.FileName;
        //        var fileLength = ByteSize.FromBytes(file.Length);

        //        while (System.IO.File.Exists(fullPath))
        //        {
        //            string tempFileName = string.Format("{0}({1})", sFileName, count++);
        //            fullPath = Path.Combine(newPath, tempFileName + sFileExtension);
        //        }

        //        ISheet sheet;
        //        using (var stream = new FileStream(fullPath, FileMode.Create))
        //        {
        //            //Masukkan file yang didownload ke folder UPLOAD...
        //            file.CopyTo(stream);
        //            stream.Position = 0;
        //            if (sFileExtension == ".xls")
        //            {
        //                HSSFWorkbook hssfwb = new HSSFWorkbook(stream); //Baca Excel 97-2000 formats  
        //                sheet = hssfwb.GetSheetAt(0); //ambil first sheet dari workbook  
        //            }
        //            else
        //            {
        //                XSSFWorkbook hssfwb = new XSSFWorkbook(stream); //Baca 2007 Excel format  
        //                sheet = hssfwb.GetSheetAt(0); //Ambil first sheet dari workbook   
        //            }
        //            IRow headerRow = sheet.GetRow(0); //Header Row
        //            int cellCount = headerRow.LastCellNum;
        //            for (int j = 0; j < cellCount; j++)
        //            {
        //                NPOI.SS.UserModel.ICell cell = headerRow.GetCell(j);
        //                if (cell == null || string.IsNullOrWhiteSpace(cell.ToString())) continue;
        //            }

        //            //Looping semua Row
        //            for (int i = (sheet.FirstRowNum + 1); i <= sheet.LastRowNum; i++) //Read Excel File
        //            {
        //                IRow row = sheet.GetRow(i);
        //                if (row == null) continue;
        //                if (row.Cells.All(d => d.CellType == CellType.Blank)) continue;

        //                //Looping 1 row untuk column
        //                for (int j = row.FirstCellNum; j < cellCount; j++)
        //                {
        //                    if (row.GetCell(j) != null)
        //                    {
        //                        dataArray.Add(row.GetCell(j).ToString());
        //                    }
        //                    else
        //                    {
        //                        dataArray.Add("");
        //                    }
        //                }
        //                try
        //                {
        //                    if (_repository.CheckTagihanData(dataArray[0], dataArray[1], dataArray[2], dataArray[3]))
        //                    {
        //                        dataArray.Clear();
        //                        continue;
        //                    }

        //                    ////Masukkin data array kedalam model
        //                    Tagihan dataTagihan = new Tagihan()
        //                    {
        //                        PhoneNumber = dataArray[0],
        //                        Name = dataArray[1],
        //                        ApplicationName = dataArray[2],
        //                        IDNumber = dataArray[3],
        //                        Log = dataArray[4],
        //                        LogDescription = dataArray[5],
        //                        LogUpdateTime = DateTime.Parse(dataArray[6]),
        //                        DateReminder = DateTime.Parse(dataArray[7]),
        //                        DateOverdue = Convert.ToInt32(dataArray[8]),
        //                        DateRequested = DateTime.Parse(dataArray[9]),
        //                        Notes = dataArray[10],
        //                        Planning = dataArray[11],
        //                        TotalAmount = Convert.ToInt32(dataArray[12]),
        //                        TotalReturn = Convert.ToInt32(dataArray[13]),
        //                        PaymentLink = dataArray[14],
        //                    };
        //                    _repository.CreateTagihan(dataTagihan);
        //                    dataArray.Clear();
        //                }
        //                catch (Exception ex)
        //                {
        //                    var logModel = new ActivityLog()
        //                    {
        //                        CreatedTime = DateTime.Now,
        //                        Description = ex.Message + ex.StackTrace,
        //                        Type = Utility.LogError,
        //                        TypeName = "ERROR",
        //                        Module = "Tagihan_ImportExcel"
        //                    };
        //                    _repository.CreateActivityLog(logModel);

        //                    var ppl = new Tagihan()
        //                    {
        //                        PhoneNumber = dataArray[0],
        //                        Name = dataArray[1],
        //                        ApplicationName = dataArray[2],
        //                        IDNumber = dataArray[3]
        //                    };
        //                    errorTagihan.Add(ppl);
        //                    dataArray.Clear();
        //                }
        //            }

        //            var TagihanImport = new TagihanImport()
        //            {
        //                CreatedTime = DateTime.Now,
        //                DownloadPath = fileUrl,
        //                FilePath = fullPath,
        //                FileName = file.FileName,
        //                FileSize = Convert.ToInt32(fileLength.KiloBytes),
        //                FileType = file.ContentType,
        //                CreatedBy_Id = 0
        //            };
        //            _repository.CreateTagihanImport(TagihanImport);
        //        }
        //    }

        //    if (errorTagihan.Any())
        //    {
        //        ViewBag.ErrorTagihan = errorTagihan;
        //    }
        //    return View("Index");
        //}

        //[HttpPost]
        //public IActionResult UploadFile(IFormFile file, int TagihanId)
        //{
        //    string folderName = "Files";
        //    string webRootPath = _hostingEnvironment.WebRootPath;
        //    string newPath = Path.Combine(webRootPath, folderName);
        //    StringBuilder sb = new StringBuilder();
        //    if (!Directory.Exists(newPath))
        //    {
        //        Directory.CreateDirectory(newPath);
        //    }
        //    if (file != null)
        //    {
        //        int count = 1;
        //        List<string> dataArray = new List<string>();
        //        string sFileExtension = Path.GetExtension(file.FileName).ToLower();
        //        string sFileName = Path.GetFileNameWithoutExtension(file.FileName);
        //        string fullPath = Path.Combine(newPath, file.FileName);
        //        string fileUrl = MyHttpContext.AppBaseUrl + "/" + folderName + "/" + file.FileName;
        //        var fileLength = ByteSize.FromBytes(file.Length);

        //        while (System.IO.File.Exists(fullPath))
        //        {
        //            string tempFileName = string.Format("{0}({1})", sFileName, count++);
        //            fullPath = Path.Combine(newPath, tempFileName + sFileExtension);
        //        }

src/DataCollection/Views/Tagihan/Create.cshtml
@{
    ViewBag.Title = "Menambahkan Tagihan";
}

@model Tagihan

<div class="pageheader">
    <div class="pageicon"><span class="fa fa-money"></span></div>
    <div class="pagetitle">
        <h1>Tagihan</h1>
        <h5>Menambah Tagihan</h5>
    </div>
</div><!--pageheader-->

<div class="maincontent">
    <div class="maincontentinner">
        <div class="row-fluid">
            <div class="widget">
                <h4 class="widgettitle">Menambah Tagihan</h4>
                <div class="widgetcontent">
                    @using (Html.BeginForm("Create", "Tagihan", FormMethod.Post, new { id = "DialogForm", @class = "stdform" }))
                    {
                        if (ViewBag.EnableErrorSummary == true)
                        {
                            <div class="panel panel-danger">
                                <header class="panel-heading">
                                    <h4 class="panel-title">Daftar Error</h4>
                                </header>
                                <div class="panel-body">
                                    <div asp-validation-summary="All"></div>
                                </div>
                            </div><!-- .widget -->
                        }

                        <p>
                            <label>Nama PIC</label>
                            <span class="field">@Html.Kendo().DropDownListFor(x => x.NamaPenagih).HtmlAttributes(new { Id = "NamaPenagih", @style = "width:100%" }).BindTo(ViewBag.NamaPIC)</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Nama Aplikasi</label>
                            <span class="field">@Html.Kendo().DropDownListFor(x => x.NamaAplikasi).HtmlAttributes(new { Id = "NamaAplikasi", @style = "width:100%" }).BindTo(ViewBag.NamaAplikasi)</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>User Aplikasi</label>
                            <span class="field">
                                @(Html.Kendo().DropDownListFor(x => x.UserAplikasi)
                                              .DataTextField("Name")
                                              .DataValueField("Name")
                                              .DataSource(source =>
                                              {
                                                  source
                                                      .Read(read =>
                                                      {
                                                          read.Action("GetUserAplikasiData", "Tagihan")
                                                              .Data("UserAplikasiData");
                                                      })
                                                      .ServerFiltering(true);
                                              })
                                              //.AutoBind(false)
                                              .CascadeFrom("NamaAplikasi")
                                              .HtmlAttributes(new { @style="width:100%"})
                                )
                            </span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Nama Nasabah</label>
                            <span class="field">@Html.TextBoxFor(x => x.NamaNasabah, new { @class = "form-control", @placeholder = "Nama Nasabah" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>ID Number</label>
                            <span class="field">@Html.TextBoxFor(x => x.IDNumber, new { @class = "form-control", @placeholder = "ID Number" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Nomor Telepon</label>
                            <span class="field">@Html.TextBoxFor(x => x.NomorTelepon, new { @class = "form-control", @placeholder = "Nomor Telepon" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Atas Nama</label>
                            <span class="field">@Html.TextBoxFor(x => x.NomorTeleponNama, new { @class = "form-control", @placeholder = "Atas Nama" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Tagihan Pokok</label>
                            <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.TagihanPokok).Format("#").Min(0).Value(0).HtmlAttributes(new { @placeholder = "Tagihan Pokok" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Tagihan Terbayar</label>
                            <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.TagihanTerbayar).Format("#").Min(0).Value(0).HtmlAttributes(new { @placeholder = "Tagihan Terbayar" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Telat</label>
                            <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.Telat).Format("#").Max(1000).Value(0).HtmlAttributes(new { @placeholder = "Telat" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Tanggal Pembayaran</label>
                            @if (User.IsInRole("Admin"))
                            {
                                <span class="field">@Html.Kendo().DatePickerFor(x => x.TanggalPembayaran).Value(DateTime.Now)</span>
                            }
                            else
                            {
                                <span class="field">@Html.Kendo().DatePickerFor(x => x.TanggalPembayaran).Value(DateTime.Now).Max(DateTime.Now).Min(DateTime.Now.AddDays(- ViewBag.MaxHariTagihan))</span>
                            }
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Tipe Pembayaran</label>
                            <span class="field">@Html.Kendo().DropDownListFor(x => x.TipePembayaran).HtmlAttributes(new { Id = "TipePembayaran", @style = "width:100%" }).BindTo(ViewBag.TipePembayaran)</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>File Attachment</label>
                            <span class="field">@Html.Kendo().Upload().Name("Files")</span>
                            <small class="desc">* Required</small>
                        </p>

                        <p class="stdformbutton">
                            <button class="btn btn-success" onclick="Create()">Simpan</button>
                            <a class="btn btn-danger" onclick="location.href='/Tagihan/Index'; return false;">Kembali</a>
                        </p>
                    }
                </div><!--widgetcontent-->
            </div><!--widget-->
        </div>
    </div>
</div>

<script>
    var ddlNamaAplikasi = $("#NamaAplikasi").data("kendoDropDownList");

    function UserAplikasiData() {
        return {
            //text: $("#UserAplikasi").val(),
            namaAplikasi: $("#NamaAplikasi").data("kendoDropDownList").value()
        };
    }
</script>

src/DataCollection/Views/Tagihan/Edit.cshtml
@{
    ViewBag.Title = "Mengubah Tagihan";
}

@model Tagihan

<div class="pageheader">
    <div class="pageicon"><span class="fa fa-money"></span></div>
    <div class="pagetitle">
        <h1>Tagihan</h1>
        <h5>Mengubah Tagihan</h5>
    </div>
</div><!--pageheader-->

<div class="maincontent">
    <div class="maincontentinner">
        <div class="row-fluid">
            <div class="widget">
                <h4 class="widgettitle">Mengubah Tagihan</h4>
                <div class="widgetcontent">
                    @using (Html.BeginForm("Edit", "Tagihan", FormMethod.Post, new { id = "DialogForm", @class = "stdform" }))
                    {
                        if (ViewBag.EnableErrorSummary == true)
                        {
                            <div class="panel panel-danger">
                                <header class="panel-heading">
                                    <h4 class="panel-title">Daftar Error</h4>
                                </header>
                                <div class="panel-body">
                                    <div asp-validation-summary="All"></div>
                                </div>
                            </div><!-- .widget -->
                        }
                        @Html.HiddenFor(x => x.CreatedTime)
                        @Html.HiddenFor(x => x.CreatedBy_Name)
                        @Html.HiddenFor(x => x.Id)
                        @Html.HiddenFor(x => x.KomisiNominal)
                        @Html.HiddenFor(x => x.KomisiPercent)
                        <p>
                            <label>Nama PIC</label>
                            <span class="field">@Html.Kendo().DropDownListFor(x => x.NamaPenagih).HtmlAttributes(new { Id = "NamaPenagih", @style = "width:100%" }).BindTo(ViewBag.NamaPIC)</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Nama Aplikasi</label>
                            <span class="field">@Html.Kendo().DropDownListFor(x => x.NamaAplikasi).HtmlAttributes(new { Id = "NamaAplikasi", @style = "width:100%" }).BindTo(ViewBag.NamaAplikasi)</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>User Aplikasi</label>
                            <span class="field">
                                @(Html.Kendo().DropDownListFor(x => x.UserAplikasi)
                                              .DataTextField("Name")
                                              .DataValueField("Name")
                                              .DataSource(source =>
                                              {
                                                  source
                                                      .Read(read =>
                                                      {
                                                          read.Action("GetUserAplikasiData", "Tagihan")
                                                              .Data("UserAplikasiData");
                                                      })
                                                      .ServerFiltering(true);
                                              })
                                              //.AutoBind(false)
                                              .CascadeFrom("NamaAplikasi")
                                              .HtmlAttributes(new { @style = "width:100%" })
                                )
                            </span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Nama Nasabah</label>
                            <span class="field">@Html.TextBoxFor(x => x.NamaNasabah, new { @class = "form-control", @placeholder = "Nama Nasabah" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>ID Number</label>
                            <span class="field">@Html.TextBoxFor(x => x.IDNumber, new { @class = "form-control", @placeholder = "ID Number" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Tagihan Pokok</label>
                            <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.TagihanPokok).Format("#").Min(0).HtmlAttributes(new { @placeholder = "Tagihan Pokok" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Tagihan Terbayar</label>
                            <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.TagihanTerbayar).Format("#").Min(0).HtmlAttributes(new { @placeholder = "Tagihan Terbayar" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Nomor Telepon</label>
                            <span class="field">@Html.TextBoxFor(x => x.NomorTelepon, new { @class = "form-control", @placeholder = "Nomor Telepon" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Atas Nama</label>
                            <span class="field">@Html.TextBoxFor(x => x.NomorTeleponNama, new { @class = "form-control", @placeholder = "Atas Nama" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Telat</label>
                            <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.Telat).Max(1000).Format("#").HtmlAttributes(new { @placeholder = "Telat" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Tanggal Pembayaran</label>
                            @if (User.IsInRole("Admin"))
                            {
                                <span class="field">@Html.Kendo().DatePickerFor(x => x.TanggalPembayaran).Value(DateTime.Now)</span>
                            }
                            else
                            {
                                <span class="field">@Html.Kendo().DatePickerFor(x => x.TanggalPembayaran).Value(DateTime.Now).Max(DateTime.Now).Min(DateTime.Now.AddDays(- ViewBag.MaxHariTagihan))</span>
                            }
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Tipe Pembayaran</label>
                            <span class="field">@Html.Kendo().DropDownListFor(x => x.TipePembayaran).HtmlAttributes(new { Id = "TipePembayaran", @style = "width:100%" }).BindTo(ViewBag.TipePembayaran)</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>File Attachment</label>
                            <span class="field">@Html.Kendo().Upload().Name("Files")</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p class="stdformbutton">
                            <button class="btn btn-success" onclick="Create()">Simpan</button>
                            <a class="btn btn-danger" onclick="location.href='/Tagihan/Index'; return false;">Kembali</a>
                        </p>
                    }
                </div><!--widgetcontent-->
            </div><!--widget-->
        </div>
    </div>
</div>

<script>
    var ddlNamaAplikasi = $("#NamaAplikasi").data("kendoDropDownList");

    function UserAplikasiData() {
        return {
            namaAplikasi: $("#NamaAplikasi").data("kendoDropDownList").value()
        };
    }
</script>