src/DataCollection/Models/People.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DataCollection.Models
{
    public class People
    {
        public int Id { get; set; }
        [DisplayName("Nama")]
        public string Name { get; set; }
        [DisplayName("Nama Aplikasi")]
        public string ApplicationName { get; set; }
        [DisplayName("Nomor ID")]
        public string IDNumber { get; set; }
        [DisplayName("Nomor Telepon")]
        public string PhoneNumber { get; set; }
        [DisplayName("Log")]
        public string Log { get; set; }
        [DisplayName("Jenis Log")]
        public string LogDescription { get; set; }

        [DataType(DataType.Date)]
        [DisplayName("Waktu Pembaruan Log")]
        public DateTime LogUpdateTime { get; set; }

        [DataType(DataType.Date)]
        [DisplayName("Waktu Pengingat")]
        public DateTime DateReminder { get; set; }
        [DisplayName("Hari Waktu Terlewat")]
        public int DateOverdue { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Waktu Meminta")]
        public DateTime DateRequested { get; set; }
        [DisplayName("Catatan")]
        public string Notes { get; set; }
        [DisplayName("Rencana")]
        public string Planning { get; set; }

        [DisplayFormat(DataFormatString = "{0:C0}")]
        [DisplayName("Jumlah Total")]
        public int TotalAmount { get; set; }

        [DisplayFormat(DataFormatString = "{0:C0}")]
        [DisplayName("Jumlah Pengembalian")]
        public int TotalReturn { get; set; }

        public string PaymentLink { get; set; }
        public string KtpPath { get; set; }
        public string KkPath { get; set; }

    }
}

src/DataCollection/Controllers/PeopleController.cs
using DataCollection.Models;
using DataCollection.ViewModels;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using OfficeOpenXml;
using OfficeOpenXml.Table;
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using NPOI.SS.UserModel;
using NPOI.HSSF.UserModel;
using NPOI.XSSF.UserModel;

namespace DataCollection.Controllers
{
    [Authorize]
    public class PeopleController : ParentController
    {
        private IHostingEnvironment _hostingEnvironment;
        private const string XlsxContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        private readonly IMapper _mapper;
        private IModelRepository _repository;
        private ILogger<PeopleController> _logger;

        public PeopleController(IModelRepository Repository, IMapper Mapper, ILogger<PeopleController> Logger, 
            IHostingEnvironment hostingEnvironment)
        {
            _repository = Repository;
            _logger = Logger;
            _mapper = Mapper;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpPost]
        public IActionResult ImportExcel(IFormFile file)
        {
            var errorPeople = new List<People>();
            string folderName = "UploadExcel";
            string webRootPath = _hostingEnvironment.WebRootPath;
            string newPath = Path.Combine(webRootPath, folderName);
            StringBuilder sb = new StringBuilder();
            if (!Directory.Exists(newPath))
            {
                Directory.CreateDirectory(newPath);
            }
            if (file != null)
            {
                int count = 1;
                List<string> dataArray = new List<string>();
                string sFileExtension = Path.GetExtension(file.FileName).ToLower();
                string sFileName = Path.GetFileNameWithoutExtension(file.FileName);
                string fullPath = Path.Combine(newPath, file.FileName);
                string fileUrl = MyHttpContext.AppBaseUrl + "/" + folderName + "/" + file.FileName;
                var fileLength = ByteSize.FromBytes(file.Length);

                while (System.IO.File.Exists(fullPath))
                {
                    string tempFileName = string.Format("{0}({1})", sFileName, count++);
                    fullPath = Path.Combine(newPath, tempFileName + sFileExtension);
                }

                ISheet sheet;
                using (var stream = new FileStream(fullPath, FileMode.Create))
                {
                    //Masukkan file yang didownload ke folder UPLOAD...
                    file.CopyTo(stream);
                    stream.Position = 0;
                    if (sFileExtension == ".xls")
                    {
                        HSSFWorkbook hssfwb = new HSSFWorkbook(stream); //Baca Excel 97-2000 formats  
                        sheet = hssfwb.GetSheetAt(0); //ambil first sheet dari workbook  
                    }
                    else
                    {
                        XSSFWorkbook hssfwb = new XSSFWorkbook(stream); //Baca 2007 Excel format  
                        sheet = hssfwb.GetSheetAt(0); //Ambil first sheet dari workbook   
                    }
                    IRow headerRow = sheet.GetRow(0); //Header Row
                    int cellCount = headerRow.LastCellNum;
                    for (int j = 0; j < cellCount; j++)
                    {
                        NPOI.SS.UserModel.ICell cell = headerRow.GetCell(j);
                        if (cell == null || string.IsNullOrWhiteSpace(cell.ToString())) continue;
                    }

                    //Looping semua Row
                    for (int i = (sheet.FirstRowNum + 1); i <= sheet.LastRowNum; i++) //Read Excel File
                    {
                        IRow row = sheet.GetRow(i);
                        if (row == null) continue;
                        if (row.Cells.All(d => d.CellType == CellType.Blank)) continue;

                        //Looping 1 row untuk column
                        for (int j = row.FirstCellNum; j < cellCount; j++)
                        {
                            if (row.GetCell(j) != null)
                            {
                                dataArray.Add(row.GetCell(j).ToString());
                            }
                            else
                            {
                                dataArray.Add("");
                            }
                        }
                        try
                        {
                            if (_repository.CheckPeopleData(dataArray[0], dataArray[1], dataArray[2], dataArray[3]))
                            {
                                dataArray.Clear();
                                continue;
                            }

                            ////Masukkin data array kedalam model
                            People dataPeople = new People()
                            {
                                PhoneNumber = dataArray[0],
                                Name = dataArray[1],
                                ApplicationName = dataArray[2],
                                IDNumber = dataArray[3],
                                Log = dataArray[4],
                                LogDescription = dataArray[5],
                                LogUpdateTime = DateTime.Parse(dataArray[6]),
                                DateReminder = DateTime.Parse(dataArray[7]),
                                DateOverdue = Convert.ToInt32(dataArray[8]),
                                DateRequested = DateTime.Parse(dataArray[9]),
                                Notes = dataArray[10],
                                Planning = dataArray[11],
                                TotalAmount = Convert.ToInt32(dataArray[12]),
                                TotalReturn = Convert.ToInt32(dataArray[13]),
                                PaymentLink = dataArray[14],
                            };
                            _repository.CreatePeople(dataPeople);
                            dataArray.Clear();
                        }
                        catch (Exception ex)
                        {
                            var logModel = new ActivityLog()
                            {
                                CreatedTime = DateTime.Now,
                                Description = ex.Message + ex.StackTrace,
                                Type = Utility.LogError,
                                TypeName = "ERROR",
                                Module = "People_ImportExcel"
                            };
                            _repository.CreateActivityLog(logModel);

                            var ppl = new People()
                            {
                                PhoneNumber = dataArray[0],
                                Name = dataArray[1],
                                ApplicationName = dataArray[2],
                                IDNumber = dataArray[3]
                            };
                            errorPeople.Add(ppl);
                            dataArray.Clear();
                        }
                    }

                    var peopleImport = new PeopleImport()
                    {
                        CreatedTime = DateTime.Now,
                        DownloadPath = fileUrl,
                        FilePath = fullPath,
                        FileName = file.FileName,
                        FileSize = Convert.ToInt32(fileLength.KiloBytes),
                        FileType = file.ContentType,
                        CreatedBy_Id = 0
                    };
                    _repository.CreatePeopleImport(peopleImport);
                }
            }

            if (errorPeople.Any())
            {
                ViewBag.ErrorPeople = errorPeople;
            }
            return View("Index");
        }

        [HttpPost]
        public IActionResult UploadFile(IFormFile file, int PeopleId)
        {
            string folderName = "Files";
            string webRootPath = _hostingEnvironment.WebRootPath;
            string newPath = Path.Combine(webRootPath, folderName);
            StringBuilder sb = new StringBuilder();
            if (!Directory.Exists(newPath))
            {
                Directory.CreateDirectory(newPath);
            }
            if (file != null)
            {
                int count = 1;
                List<string> dataArray = new List<string>();
                string sFileExtension = Path.GetExtension(file.FileName).ToLower();
                string sFileName = Path.GetFileNameWithoutExtension(file.FileName);
                string fullPath = Path.Combine(newPath, file.FileName);
                string fileUrl = MyHttpContext.AppBaseUrl + "/" + folderName + "/" + file.FileName;
                var fileLength = ByteSize.FromBytes(file.Length);

                while (System.IO.File.Exists(fullPath))
                {
                    string tempFileName = string.Format("{0}({1})", sFileName, count++);
                    fullPath = Path.Combine(newPath, tempFileName + sFileExtension);
                }

                using (var stream = new FileStream(fullPath, FileMode.Create))
                {
                    //Masukkan file yang didownload ke folder UPLOAD...
                    file.CopyTo(stream);
                    stream.Position = 0;
                }

                var model = new Files()
                {
                    CreatedTime = DateTime.Now,
                    DownloadPath = fileUrl,

src/DataCollection/Views/People/Create.cshtml
@{
    ViewBag.Title = "Menambahkan People";
}

@model People

<script>

</script>

<div class="pageheader">
    <div class="pageicon"><span class="fa fa-users"></span></div>
    <div class="pagetitle">
        <h1>People</h1>
        <h5>Menambah People</h5>
    </div>
</div><!--pageheader-->

<div class="maincontent">
    <div class="maincontentinner">
        <div class="row-fluid">
            <div class="widget">
                <h4 class="widgettitle">Menambah People</h4>
                <div class="widgetcontent">
                    @using (Html.BeginForm("Create", "People", FormMethod.Post, new { id = "DialogForm", @class = "stdform" }))
                    {
                        if (ViewBag.EnableErrorSummary == true)
                        {
                            <div class="panel panel-danger">
                                <header class="panel-heading">
                                    <h4 class="panel-title">Daftar Error</h4>
                                </header>
                                <div class="panel-body">
                                    <div asp-validation-summary="All"></div>
                                </div>
                            </div><!-- .widget -->
                        }
                        @(Html.Kendo().TabStrip()
                                    .Name("tabstrip")
                                    .Animation(animation =>
                                        animation.Open(effect =>
                                            effect.Fade(FadeDirection.In)))
                                    .Items(tabstrip =>
                                    {
                                        tabstrip.Add().Text("Informasi People")
                                                .Selected(true)
                                                .Content(@<text>
                                            <p>
                                                <label>Nama Orang</label>
                                                <span class="field">@Html.TextBoxFor(x => x.Name, new { @class = "form-control", @placeholder = "Nama Orang" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Nama Aplikasi</label>
                                                <span class="field">@Html.TextBoxFor(x => x.ApplicationName, new { @class = "form-control", @placeholder = "Nama Aplikasi" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>ID Number</label>
                                                <span class="field">@Html.TextBoxFor(x => x.IDNumber, new { @class = "form-control", @placeholder = "ID Number" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Nomor Telepon</label>
                                                <span class="field">@Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control", @placeholder = "Nomor Telepon" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Log</label>
                                                <span class="field">@Html.TextBoxFor(x => x.Log, new { @class = "form-control", @placeholder = "Nama Orang" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Log Description</label>
                                                <span class="field">@Html.TextBoxFor(x => x.LogDescription, new { @class = "form-control", @placeholder = "Nama Orang" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Log Update Time</label>
                                                <span class="field">@Html.Kendo().DatePickerFor(x => x.LogUpdateTime)</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Date Reminder</label>
                                                <span class="field">@Html.Kendo().DatePickerFor(x => x.DateReminder)</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Jumlah Keterlambatan</label>
                                                <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.DateOverdue).Min(0).Value(0).HtmlAttributes(new { @placeholder = "Jumlah Keterlambatan" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Tanggal Permintaan</label>
                                                <span class="field">@Html.Kendo().DatePickerFor(x => x.DateRequested)</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Keterangan</label>
                                                <span class="field">@Html.TextBoxFor(x => x.Notes, new { @class = "form-control", @placeholder = "Keterangan" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Rencana</label>
                                                <span class="field">@Html.TextBoxFor(x => x.Planning, new { @class = "form-control", @placeholder = "Rencana" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                             <p>
                                                 <label>Link Pembayaran</label>
                                                 <span class="field">@Html.TextBoxFor(x => x.PaymentLink, new { @class = "form-control", @placeholder = "Link Pembayaran" })</span>
                                                 <small class="desc">* Required</small>
                                             </p>
                                            <p>
                                                <label>Total Pembayaran</label>
                                                <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.TotalAmount).Min(0).Value(0).HtmlAttributes(new { @placeholder = "Total Pembayaran" })</span>
                                            </p>
                                             <p>
                                                 <label>Total Pengembalian</label>
                                                 <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.TotalReturn).Min(0).Value(0).HtmlAttributes(new { @placeholder = "Total Pengembalian" })</span>
                                             </p>
                                            <p class="stdformbutton">
                                                <button class="btn btn-success" onclick="Create()">Simpan</button>
                                                <a class="btn btn-danger" onclick="location.href='Index'; return false;">Kembali</a>
                                            </p>
                                                </text>);
                                                                    })
                        )
                    }
                </div><!--widgetcontent-->
            </div><!--widget-->
        </div>
    </div>
</div>

src/DataCollection/Views/People/Edit.cshtml
@{
    ViewBag.Title = "Mengubah People";
}

@model People

<script>

</script>

<div class="pageheader">
    <div class="pageicon"><span class="fa fa-users"></span></div>
    <div class="pagetitle">
        <h1>People</h1>
        <h5>Mengubah People</h5>
    </div>
</div><!--pageheader-->

<div class="maincontent">
    <div class="maincontentinner">
        <div class="row-fluid">
            <div class="widget">
                <h4 class="widgettitle">Mengubah People</h4>
                <div class="widgetcontent">
                    @using (Html.BeginForm("Edit", "People", FormMethod.Post, new { id = "DialogForm", @class = "stdform" }))
                    {
                        if (ViewBag.EnableErrorSummary == true)
                        {
                            <div class="panel panel-danger">
                                <header class="panel-heading">
                                    <h4 class="panel-title">Daftar Error</h4>
                                </header>
                                <div class="panel-body">
                                    <div asp-validation-summary="All"></div>
                                </div>
                            </div><!-- .widget -->
                        }
                        @(Html.Kendo().TabStrip()
                                    .Name("tabstrip")
                                    .Animation(animation =>
                                        animation.Open(effect =>
                                            effect.Fade(FadeDirection.In)))
                                    .Items(tabstrip =>
                                    {
                                        tabstrip.Add().Text("Informasi People")
                                                .Selected(true)
                                                .Content(@<text>
                                            @Html.HiddenFor(x => x.Id)                 
                                            <p>
                                                <label>Nama Orang</label>
                                                <span class="field">@Html.TextBoxFor(x => x.Name, new { @class = "form-control", @placeholder = "Nama Orang" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Nama Aplikasi</label>
                                                <span class="field">@Html.TextBoxFor(x => x.ApplicationName, new { @class = "form-control", @placeholder = "Nama Aplikasi" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>ID Number</label>
                                                <span class="field">@Html.TextBoxFor(x => x.IDNumber, new { @class = "form-control", @placeholder = "ID Number" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Nomor Telepon</label>
                                                <span class="field">@Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control", @placeholder = "Nomor Telepon" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Log</label>
                                                <span class="field">@Html.TextBoxFor(x => x.Log, new { @class = "form-control", @placeholder = "Nama Orang" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Log Description</label>
                                                <span class="field">@Html.TextBoxFor(x => x.LogDescription, new { @class = "form-control", @placeholder = "Nama Orang" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Log Update Time</label>
                                                <span class="field">@Html.Kendo().DatePickerFor(x => x.LogUpdateTime)</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Date Reminder</label>
                                                <span class="field">@Html.Kendo().DatePickerFor(x => x.DateReminder)</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Jumlah Keterlambatan</label>
                                                <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.DateOverdue).Min(0).HtmlAttributes(new { @placeholder = "Jumlah Keterlambatan" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Tanggal Permintaan</label>
                                                <span class="field">@Html.Kendo().DatePickerFor(x => x.DateRequested)</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Keterangan</label>
                                                <span class="field">@Html.TextBoxFor(x => x.Notes, new { @class = "form-control", @placeholder = "Keterangan" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                            <p>
                                                <label>Rencana</label>
                                                <span class="field">@Html.TextBoxFor(x => x.Planning, new { @class = "form-control", @placeholder = "Rencana" })</span>
                                                <small class="desc">* Required</small>
                                            </p>
                                             <p>
                                                 <label>Link Pembayaran</label>
                                                 <span class="field">@Html.TextBoxFor(x => x.PaymentLink, new { @class = "form-control", @placeholder = "Link Pembayaran" })</span>
                                                 <small class="desc">* Required</small>
                                             </p>
                                            <p>
                                                <label>Total Pembayaran</label>
                                                <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.TotalAmount).Min(0).HtmlAttributes(new { @placeholder = "Total Pembayaran" })</span>
                                            </p>
                                             <p>
                                                 <label>Total Pengembalian</label>
                                                 <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.TotalReturn).Min(0).HtmlAttributes(new { @placeholder = "Total Pengembalian" })</span>
                                             </p>
                                            <p class="stdformbutton">
                                                <button class="btn btn-success" onclick="Create()">Simpan</button>
                                                <a class="btn btn-danger" onclick="location.href='Index'; return false;">Kembali</a>
                                            </p>
                                                </text>);
                                                                    })
                        )
                    }
                </div><!--widgetcontent-->
            </div><!--widget-->
        </div>
    </div>
</div>