src/DataCollection/Models/Insentif.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DataCollection.Models
{
    public class Insentif
    {
        public int Id { get; set; }

        [DisplayName("Nilai Minimal Tagihan")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        public int MinimalTagihan { get; set; }

        [DisplayName("Nilai Maksimal Tagihan")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        public int MaksimalTagihan { get; set; }

        [DisplayName("Maksimal Telat")]
        public int MaksimalTelat { get; set; }

        [DisplayName("Nilai Insentif")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        public int NilaiInsentif { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy H:mm:ss}")]
        public DateTime CreatedTime { get; set; }

        public string CreatedBy_Name { get; set; }
    }
}

src/DataCollection/Controllers/InsentifController.cs
using DataCollection.Models;
using DataCollection.ViewModels;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using OfficeOpenXml;
using OfficeOpenXml.Table;
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using NPOI.SS.UserModel;
using NPOI.HSSF.UserModel;
using NPOI.XSSF.UserModel;
using System.ComponentModel;
using FastMember;
using System.Globalization;
using System.Threading;

namespace DataCollection.Controllers
{
    [Authorize(Policy = "Admin")]
    public class InsentifController : ParentController
    {
        private IHostingEnvironment _hostingEnvironment;
        private const string XlsxContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        private readonly IMapper _mapper;
        private IModelRepository _repository;
        private ILogger<InsentifController> _logger;

        public InsentifController(IModelRepository Repository, IMapper Mapper, ILogger<InsentifController> Logger, 
            IHostingEnvironment hostingEnvironment)
        {
            _repository = Repository;
            _logger = Logger;
            _mapper = Mapper;
            _hostingEnvironment = hostingEnvironment;
        }

        //[HttpPost]
        //public IActionResult ImportExcel(IFormFile file)
        //{
        //    var errorInsentif = new List<Insentif>();
        //    string folderName = "UploadExcel";
        //    string webRootPath = _hostingEnvironment.WebRootPath;
        //    string newPath = Path.Combine(webRootPath, folderName);
        //    StringBuilder sb = new StringBuilder();
        //    if (!Directory.Exists(newPath))
        //    {
        //        Directory.CreateDirectory(newPath);
        //    }
        //    if (file != null)
        //    {
        //        int count = 1;
        //        List<string> dataArray = new List<string>();
        //        string sFileExtension = Path.GetExtension(file.FileName).ToLower();
        //        string sFileName = Path.GetFileNameWithoutExtension(file.FileName);
        //        string fullPath = Path.Combine(newPath, file.FileName);
        //        string fileUrl = MyHttpContext.AppBaseUrl + "/" + folderName + "/" + file.FileName;
        //        var fileLength = ByteSize.FromBytes(file.Length);

        //        while (System.IO.File.Exists(fullPath))
        //        {
        //            string tempFileName = string.Format("{0}({1})", sFileName, count++);
        //            fullPath = Path.Combine(newPath, tempFileName + sFileExtension);
        //        }

        //        ISheet sheet;
        //        using (var stream = new FileStream(fullPath, FileMode.Create))
        //        {
        //            //Masukkan file yang didownload ke folder UPLOAD...
        //            file.CopyTo(stream);
        //            stream.Position = 0;
        //            if (sFileExtension == ".xls")
        //            {
        //                HSSFWorkbook hssfwb = new HSSFWorkbook(stream); //Baca Excel 97-2000 formats  
        //                sheet = hssfwb.GetSheetAt(0); //ambil first sheet dari workbook  
        //            }
        //            else
        //            {
        //                XSSFWorkbook hssfwb = new XSSFWorkbook(stream); //Baca 2007 Excel format  
        //                sheet = hssfwb.GetSheetAt(0); //Ambil first sheet dari workbook   
        //            }
        //            IRow headerRow = sheet.GetRow(0); //Header Row
        //            int cellCount = headerRow.LastCellNum;
        //            for (int j = 0; j < cellCount; j++)
        //            {
        //                NPOI.SS.UserModel.ICell cell = headerRow.GetCell(j);
        //                if (cell == null || string.IsNullOrWhiteSpace(cell.ToString())) continue;
        //            }

        //            //Looping semua Row
        //            for (int i = (sheet.FirstRowNum + 1); i <= sheet.LastRowNum; i++) //Read Excel File
        //            {
        //                IRow row = sheet.GetRow(i);
        //                if (row == null) continue;
        //                if (row.Cells.All(d => d.CellType == CellType.Blank)) continue;

        //                //Looping 1 row untuk column
        //                for (int j = row.FirstCellNum; j < cellCount; j++)
        //                {
        //                    if (row.GetCell(j) != null)
        //                    {
        //                        dataArray.Add(row.GetCell(j).ToString());
        //                    }
        //                    else
        //                    {
        //                        dataArray.Add("");
        //                    }
        //                }
        //                try
        //                {
        //                    if (_repository.CheckInsentifData(dataArray[0], dataArray[1], dataArray[2], dataArray[3]))
        //                    {
        //                        dataArray.Clear();
        //                        continue;
        //                    }

        //                    ////Masukkin data array kedalam model
        //                    Insentif dataInsentif = new Insentif()
        //                    {
        //                        PhoneNumber = dataArray[0],
        //                        Name = dataArray[1],
        //                        ApplicationName = dataArray[2],
        //                        IDNumber = dataArray[3],
        //                        Log = dataArray[4],
        //                        LogDescription = dataArray[5],
        //                        LogUpdateTime = DateTime.Parse(dataArray[6]),
        //                        DateReminder = DateTime.Parse(dataArray[7]),
        //                        DateOverdue = Convert.ToInt32(dataArray[8]),
        //                        DateRequested = DateTime.Parse(dataArray[9]),
        //                        Notes = dataArray[10],
        //                        Planning = dataArray[11],
        //                        TotalAmount = Convert.ToInt32(dataArray[12]),
        //                        TotalReturn = Convert.ToInt32(dataArray[13]),
        //                        PaymentLink = dataArray[14],
        //                    };
        //                    _repository.CreateInsentif(dataInsentif);
        //                    dataArray.Clear();
        //                }
        //                catch (Exception ex)
        //                {
        //                    var logModel = new ActivityLog()
        //                    {
        //                        CreatedTime = DateTime.Now,
        //                        Description = ex.Message + ex.StackTrace,
        //                        Type = Utility.LogError,
        //                        TypeName = "ERROR",
        //                        Module = "Insentif_ImportExcel"
        //                    };
        //                    _repository.CreateActivityLog(logModel);

        //                    var ppl = new Insentif()
        //                    {
        //                        PhoneNumber = dataArray[0],
        //                        Name = dataArray[1],
        //                        ApplicationName = dataArray[2],
        //                        IDNumber = dataArray[3]
        //                    };
        //                    errorInsentif.Add(ppl);
        //                    dataArray.Clear();
        //                }
        //            }

        //            var InsentifImport = new InsentifImport()
        //            {
        //                CreatedTime = DateTime.Now,
        //                DownloadPath = fileUrl,
        //                FilePath = fullPath,
        //                FileName = file.FileName,
        //                FileSize = Convert.ToInt32(fileLength.KiloBytes),
        //                FileType = file.ContentType,
        //                CreatedBy_Id = 0
        //            };
        //            _repository.CreateInsentifImport(InsentifImport);
        //        }
        //    }

        //    if (errorInsentif.Any())
        //    {
        //        ViewBag.ErrorInsentif = errorInsentif;
        //    }
        //    return View("Index");
        //}

        //[HttpPost]
        //public IActionResult UploadFile(IFormFile file, int InsentifId)
        //{
        //    string folderName = "Files";
        //    string webRootPath = _hostingEnvironment.WebRootPath;
        //    string newPath = Path.Combine(webRootPath, folderName);
        //    StringBuilder sb = new StringBuilder();
        //    if (!Directory.Exists(newPath))
        //    {
        //        Directory.CreateDirectory(newPath);
        //    }
        //    if (file != null)
        //    {
        //        int count = 1;
        //        List<string> dataArray = new List<string>();
        //        string sFileExtension = Path.GetExtension(file.FileName).ToLower();
        //        string sFileName = Path.GetFileNameWithoutExtension(file.FileName);
        //        string fullPath = Path.Combine(newPath, file.FileName);
        //        string fileUrl = MyHttpContext.AppBaseUrl + "/" + folderName + "/" + file.FileName;
        //        var fileLength = ByteSize.FromBytes(file.Length);

        //        while (System.IO.File.Exists(fullPath))
        //        {
        //            string tempFileName = string.Format("{0}({1})", sFileName, count++);

src/DataCollection/Views/Insentif/Create.cshtml
@{
    ViewBag.Title = "Menambahkan Insentif";
}

@model Insentif

<script>

</script>

<div class="pageheader">
    <div class="pageicon"><span class="fa fa-table"></span></div>
    <div class="pagetitle">
        <h1>Insentif</h1>
        <h5>Menambah Insentif</h5>
    </div>
</div><!--pageheader-->

<div class="maincontent">
    <div class="maincontentinner">
        <div class="row-fluid">
            <div class="widget">
                <h4 class="widgettitle">Menambah Insentif</h4>
                <div class="widgetcontent">
                    @using (Html.BeginForm("Create", "Insentif", FormMethod.Post, new { id = "DialogForm", @class = "stdform" }))
                    {
                        if (ViewBag.EnableErrorSummary == true)
                        {
                            <div class="panel panel-danger">
                                <header class="panel-heading">
                                    <h4 class="panel-title">Daftar Error</h4>
                                </header>
                                <div class="panel-body">
                                    <div asp-validation-summary="All"></div>
                                </div>
                            </div><!-- .widget -->
                        }

                        <p>
                            <label>Minimal Tagihan</label>
                            <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.MinimalTagihan).Format("#").Min(0).Value(0).HtmlAttributes(new { @placeholder = "Minimal Tagihan" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Maksimal Tagihan</label>
                            <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.MaksimalTagihan).Format("#").Min(0).Value(0).HtmlAttributes(new { @placeholder = "Maksimal Tagihan" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Maksimal Telat</label>
                            <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.MaksimalTelat).Format("#").Min(0).Value(0).HtmlAttributes(new { @placeholder = "Nilai Insentif" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Nilai Insentif</label>
                            <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.NilaiInsentif).Format("#").Min(0).Value(0).HtmlAttributes(new { @placeholder = "Nilai Insentif" })</span>
                            <small class="desc">* Required</small>
                        </p>

                        <p class="stdformbutton">
                            <button class="btn btn-success" onclick="Create()">Simpan</button>
                            <a class="btn btn-danger" onclick="location.href='/Insentif/Index'; return false;">Kembali</a>
                        </p>
                    }
                </div><!--widgetcontent-->
            </div><!--widget-->
        </div>
    </div>
</div>

src/DataCollection/Views/Insentif/Edit.cshtml
@{
    ViewBag.Title = "Mengubah Insentif";
}

@model Insentif

<script>

</script>

<div class="pageheader">
    <div class="pageicon"><span class="fa fa-table"></span></div>
    <div class="pagetitle">
        <h1>Insentif</h1>
        <h5>Mengubah Insentif</h5>
    </div>
</div><!--pageheader-->

<div class="maincontent">
    <div class="maincontentinner">
        <div class="row-fluid">
            <div class="widget">
                <h4 class="widgettitle">Mengubah Insentif</h4>
                <div class="widgetcontent">
                    @using (Html.BeginForm("Edit", "Insentif", FormMethod.Post, new { id = "DialogForm", @class = "stdform" }))
                    {
                        if (ViewBag.EnableErrorSummary == true)
                        {
                            <div class="panel panel-danger">
                                <header class="panel-heading">
                                    <h4 class="panel-title">Daftar Error</h4>
                                </header>
                                <div class="panel-body">
                                    <div asp-validation-summary="All"></div>
                                </div>
                            </div><!-- .widget -->
                        }

                        @Html.HiddenFor(x => x.Id)
                        <p>
                            <label>Minimal Tagihan</label>
                            <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.MinimalTagihan).Format("#").Min(0).HtmlAttributes(new { @placeholder = "Minimal Tagihan" })</span>QQ
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Maksimal Tagihan</label>
                            <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.MaksimalTagihan).Format("#").Min(0).HtmlAttributes(new { @placeholder = "Maksimal Tagihan" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Maksimal Telat</label>
                            <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.MaksimalTelat).Format("#").Min(0).HtmlAttributes(new { @placeholder = "Nilai Insentif" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p>
                            <label>Nilai Insentif</label>
                            <span class="field">@Html.Kendo().NumericTextBoxFor(x => x.NilaiInsentif).Format("#").Min(0).HtmlAttributes(new { @placeholder = "Nilai Insentif" })</span>
                            <small class="desc">* Required</small>
                        </p>
                        <p class="stdformbutton">
                            <button class="btn btn-success" onclick="Create()">Simpan</button>
                            <a class="btn btn-danger" onclick="location.href='/Insentif/Index'; return false;">Kembali</a>
                        </p>
                    }
                </div><!--widgetcontent-->
            </div><!--widget-->
        </div>
    </div>
</div>

src/DataCollection/Views/Insentif/Index.cshtml
@{
    ViewData["Title"] = "Daftar Insentif";
}

@section Footer {
    <script src="//cdnjs.cloudflare.com/ajax/libs/jszip/2.4.0/jszip.min.js"></script>
    <script type="text/javascript">
        var SelectedRow = "";
        var State = "create";
        var Dialog;

        function RefreshGrid() {
            var Grid = $('#Grid').data('kendoGrid');
            Grid.dataSource.read();
            SelectedRow = "";
            return false;
        }
        

        $(document).ready(function () {
            Dialog = $("<div id='window' />").appendTo("body").kendoWindow({
                title: "Title",
                animation: false,
                resizable: false,
                modal: true,
                visible: false,
                width: "100%",
                height: "100%"
            }).data("kendoWindow");

            Dialog_2 = $("<div id='window_2' />").appendTo("body").kendoWindow({
                title: "Title",
                animation: false,
                resizable: false,
                modal: true,
                visible: false,
                open: function (e) {
                    this.wrapper.css({ top: 50, left: 50 });
                }
            }).data("kendoWindow");

            $("body").delegate("#GridButtonCreate", "click", function () {
                var url = $(this).attr("href");
                window.location.href = url;
                return false;
            });

            $("body").delegate("#GridButtonEdit", "click", function () {
                if (SelectedRow.length != 1) {
                    alert("Pilih satu data saja!");
                    return false;
                }
                var url = $(this).attr("href") + "/" + SelectedRow;
                window.location.href = url;
                return false;
            });

            $("body").delegate("#GridButtonView", "click", function () {
                if (SelectedRow.length != 1) {
                    alert("Pilih satu data saja!");
                    return false;
                }
                var url = $(this).attr("href") + "/" + SelectedRow;
                window.location.href = url;
                return false;
            });

            $("body").delegate("#GridButtonDelete", "click", function () {
                if (SelectedRow.length == 0) {
                    alert("Pilih minimal satu data!");
                    return false;
                }
                if (!confirm("Anda yakin ingin menghapus " + SelectedRow.length + " data ini?")) {
                    return false;
                }
                $.ajax({
                    type: 'POST',
                    url: $(this).attr("href") + "/" + SelectedRow,
                    success: function (data) {
                        if (data == "") {
                            RefreshGrid();
                        }
                        else {
                            alert(data);
                        }
                    }
                });
                return false;
            });

        });

        var index = 0;
        var CurrentPage = 0;
        var CurrentPageSize = 0;
        function GetRowNumber() {
            return ++index;
        }

        function onDataBound() {
            for (var i = 0; i < this.columns.length; i++) {
                this.autoFitColumn(i);
            }
        }

        function onDataBinding() {
            var Grid = $("#Grid").data("kendoGrid");
            CurrentPage = Grid.dataSource.page();
            CurrentPageSize = Grid.dataSource.pageSize();
            index = ((CurrentPage - 1) * CurrentPageSize);
        }

        function onChange(e) {
            var Grid = e.sender;
            SelectedRow = $.map(this.select(), function (item) {
                return Grid.dataItem(item).Id;
            });
        }

    </script>
}
<div class="pageheader">
    <div class="pageicon"><span class="fa fa-table"></span></div>
    <div class="pagetitle">
        <h1>Insentif</h1>
        <h5>Daftar Insentif</h5>
    </div>
</div><!--pageheader-->

<div class="maincontent">
    <div class="maincontentinner">
        <div class="row-fluid">
            <button href="/Insentif/Create" class="btn btn-success" id="GridButtonCreate"><i class="fa fa-plus-circle"></i> Create</button>
            <button href="/Insentif/Edit" class="btn btn-warning" id="GridButtonEdit"><i class="fa fa-pencil"></i> Edit</button>
            <button href="/Insentif/Delete" class="btn btn-danger" id="GridButtonDelete"><i class="fa fa-trash"></i> Delete</button>
            <div>
                @(Html.Kendo().Grid<Insentif>()
                      .Name("Grid")
                      .Columns(columns =>
                      {
                          //columns.Bound(e => e.Id).Title("No").ClientTemplate("#= GetRowNumber() #").Width(35).Filterable(false).Sortable(false);
                          columns.Bound(e => e.MinimalTagihan);
                          columns.Bound(e => e.MaksimalTagihan);
                          columns.Bound(e => e.MaksimalTelat);
                          columns.Bound(e => e.NilaiInsentif);
                      })
                      .DataSource(binding => binding
                          .Ajax()
                          .Model(model => model.Id(m => m.Id))
                          .Read("Select", "Insentif")
                          .Group(x => x.Add(b => b.MaksimalTelat))
                          .PageSize(50)
                      )
                      .Groupable()
                      .Pageable()
                      .Editable(m => m.Enabled(false))
                      .Resizable(m => m.Columns(true))
                      .Sortable()
                      .Filterable(filterable => filterable
                          .Extra(false)
                          .Operators(operators => operators
                              .ForString(str => str.Clear()
                                  .Contains(Utility.GridFilter["Contains"])
                                  .DoesNotContain(Utility.GridFilter["DoesNotContain"])
                                  .IsEqualTo(Utility.GridFilter["IsEqualTo"])
                                  .IsNotEqualTo(Utility.GridFilter["IsNotEqualTo"])
                                  .StartsWith(Utility.GridFilter["StartsWith"])
                                  .EndsWith(Utility.GridFilter["EndsWith"])
                              ))
                      )
                      .Scrollable(m => m.Height(700))
                      .Selectable(selectable => selectable
                          .Mode(GridSelectionMode.Multiple)
                          .Type(GridSelectionType.Row))
                      .Events(events => events
                          .DataBound("onDataBound")
                          .DataBinding("onDataBinding")
                          .Change("onChange")
                      )
                )
            </div>
        </div><!--row-fluid-->
    </div><!--maincontentinner-->
</div><!--maincontent-->

src/DataCollection/Views/Insentif/Report.cshtml
@{
    ViewData["Title"] = "Laporan Insentif Bulanan";
}

@section Footer {
    <script type="text/javascript">
        function SubmitReport() {
            var date = kendo.toString($("#Date").data("kendoDatePicker").value(), "dd/MM/yyyy");
            var Url = '@Url.Content("~/Insentif/GetReport")' + "?Date=" +date;
            window.location.href = Url;
            return false;
        }
    </script>
}
<div class="pageheader">
    <div class="pageicon"><span class="fa fa-table"></span></div>
    <div class="pagetitle">
        <h1>Report</h1>
        <h5>Laporan Insentif Bulanan</h5>
    </div>
</div><!--pageheader-->

<div class="maincontent">
    <div class="maincontentinner">
        <div class="row-fluid">
            <div class="row">
                @Html.Kendo().DatePicker().Name("Date").Start(CalendarView.Year).Depth(CalendarView.Year).Value(DateTime.Today)
                <button onclick="SubmitReport()">Submit</button>
            </div>
        </div><!--row-fluid-->
    </div><!--maincontentinner-->
</div><!--maincontent-->